# Generated by Selenium IDE
from selenium.webdriver.chrome.options import Options
import tempfile
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
      self.driver.get("http://127.0.0.1:5000/login?next=%2Fnotepad")
      self.driver.set_window_size(878, 1184)
      self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
      self.driver.find_element(By.ID, "password").send_keys("1234")
      self.driver.find_element(By.ID, "submit").click()

      self.driver.get("http://127.0.0.1:5000/notepad/create")

      print("Ruta actual tras login:", self.driver.current_url)
      self.driver.find_element(By.ID, "title").send_keys("example")
      self.driver.find_element(By.ID, "body").send_keys("example")
      self.driver.find_element(By.ID, "submit").click()
